from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
path('admin/', admin.site.urls),
path('', views.landing_page, name='landing_page'),
path('home/', views.front_page, name='front_page'), 
path('form/', views.resume_form, name='generate_resume'),
path('resume/<int:resume_id>/', views.resume_detail, name='resume_detail'),
path('signup/', views.signup_view, name='signup'),
path('logout/', views.logout_view, name='logout'),
path('login/', views.login_view, name='login'),
path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
path('dashboard/', views.dashboard_view, name='dashboard'),
path('preferences/', views.preferences, name='preferences'),
path('preferences/add/', views.add_job_role, name='add_job_role'),
path('preferences/delete/', views.delete_job_role, name='delete_job_role'),
path('help/', views.help_view, name='help'),
path('complaint/', views.complaint_view, name='complaint'),
path('about/', views.about_view, name='about'),
path('privacy-policy/', views.privacy_policy_view, name='privacy_policy'),  
path('terms/', views.terms_view, name='terms'),
path('safety-tips/', views.safety_tips_view, name='safety_tips'),
path('resume1/create/', views.resume_form1, name='resume_form1'),
path('resume1/<int:resume_id>/', views.resume_display1, name='resume_display1'),
path('resume1/<int:resume_id>/download/', views.download_resume_pdf1, name='download_resume_pdf1'),
path('resume2/create/', views.resume_form2, name='resume_form2'),
path('resume2/<int:resume_id>/', views.resume_display2, name='resume_display2'),
path('resume2/<int:resume_id>/download/', views.download_resume_pdf2, name='download_resume_pdf2'),
path('resume3/create/', views.resume_form3, name='resume_form3'),
path('resume3/<int:resume_id>/', views.resume_display3, name='resume_display3'),
path('resume3/<int:resume_id>/download/', views.download_resume_pdf3, name='download_resume_pdf3'),
path('resume4/create/', views.resume_form4, name='resume_form4'),
path('resume4/<int:resume_id>/', views.resume_display4, name='resume_display4'),
path('resume4/<int:resume_id>/download/', views.download_resume_pdf4, name='download_resume_pdf4'),
path('resume5/create/', views.resume_form5, name='resume_form5'),
path('resume5/<int:resume_id>/', views.resume_display5, name='resume_display5'),
path('resume5/<int:resume_id>/download/', views.download_resume_pdf5, name='download_resume_pdf5'),
path('my-resumes/', views.my_resumes, name='my_resumes'),
path('resume/<str:resume_type>/<int:resume_id>/', views.resume_display, name='resume_display'),
path('dashboardd/', views.dashboard, name='dashboard'),
]