# Generated by Django 5.2.5 on 2025-11-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_pref', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('college_name', models.CharField(blank=True, max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('cgpa', models.CharField(blank=True, max_length=50)),
                ('school_10', models.CharField(blank=True, max_length=255)),
                ('year_10', models.CharField(blank=True, max_length=50)),
                ('percentage_10', models.CharField(blank=True, max_length=50)),
                ('school_12', models.CharField(blank=True, max_length=255)),
                ('year_12', models.CharField(blank=True, max_length=50)),
                ('percentage_12', models.CharField(blank=True, max_length=50)),
                ('skills', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('certificates', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('accomplishments', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
            ],
        ),
    ]
