# Generated by Django 5.2.5 on 2025-11-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_jobrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrole',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
