# Generated by Django 5.2.5 on 2025-11-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_jobrole_created_at_remove_jobrole_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('profile_summary', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
            ],
        ),
    ]
