# Generated by Django 5.2.5 on 2025-11-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True, help_text='One entry per line')),
                ('skills', models.TextField(blank=True, help_text='Comma or line-separated')),
                ('education', models.TextField(blank=True, help_text='One entry per line')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
        ),
    ]
