# Generated by Django 5.2.5 on 2025-11-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resume2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('about', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='resumes/')),
            ],
        ),
    ]
