# Generated by Django 5.2.5 on 2025-11-12 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_rename_name_resume_user_userpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume2',
            name='website',
        ),
        migrations.AddField(
            model_name='resume1',
            name='template_type',
            field=models.CharField(default='Resume1', max_length=10),
        ),
        migrations.AddField(
            model_name='resume1',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume2',
            name='template_type',
            field=models.CharField(default='Resume2', max_length=10),
        ),
        migrations.AddField(
            model_name='resume2',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume3',
            name='template_type',
            field=models.CharField(default='Resume3', max_length=10),
        ),
        migrations.AddField(
            model_name='resume3',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume4',
            name='template_type',
            field=models.CharField(default='Resume4', max_length=10),
        ),
        migrations.AddField(
            model_name='resume4',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume5',
            name='template_type',
            field=models.CharField(default='Resume5', max_length=10),
        ),
        migrations.AddField(
            model_name='resume5',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
