# Generated by Django 5.2.5 on 2025-11-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_alter_resume1_user_alter_resume2_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume1',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resume1',
            name='work_experience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
