# Generated by Django 5.2.5 on 2025-11-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_alter_resume1_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume1',
            name='education',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='resume1',
            name='work_experience',
            field=models.JSONField(default=dict),
        ),
    ]
