# Generated by Django 5.2.5 on 2025-11-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_alter_resume1_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
