# Generated by Django 5.2.5 on 2025-11-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_resume_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume4',
            name='profile_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume5',
            name='profile_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume1',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume1',
            name='work_experience',
            field=models.TextField(blank=True),
        ),
    ]
