# Generated by Django 5.2.5 on 2025-11-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_resume4_profile_summary_resume5_profile_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume1',
            name='education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume1',
            name='work_experience',
            field=models.TextField(blank=True, default=''),
        ),
    ]
