# Generated by Django 5.2.5 on 2025-11-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_alter_resume1_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume2',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
    ]
