# Generated by Django 5.2.5 on 2025-11-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_alter_resume2_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume2',
            old_name='experience',
            new_name='work_experience',
        ),
    ]
