# Generated by Django 5.2.5 on 2025-11-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_rename_experience_resume2_work_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume5',
            old_name='technical_skills',
            new_name='skills',
        ),
    ]
